### ISSUE TITLE
Redesigning the Internal Theme

### ISSUE THREAD

**Issue by JoshStrobl** [BuddiesOfBudgie/budgie-desktop#22]
This is a public issue to indicate my intent to finally redesign the internal theme. This new internal theme will be inspired by [Material Design](https://material.io/design), work from Materia and Plata, with official light and dark theming. It will feature clearer widget separation in places like Raven, *some* (not excessive) negative spacing to make components feel less cramped, and better contrast.

I would like to stress that this is a mockup. It isn't finalized (empty panel as an example) and I haven't even started working on it yet (this is something I've personally wanted to do for some time, so I'd love to be able to work on it personally, recognizing that I know this may excite many of you, but please let me do this :stuck_out_tongue:).

![mockup-v1](https://user-images.githubusercontent.com/156574/148421876-5eb673fe-877e-4437-9141-7877fae0122c.png)

I am entirely open to refinement to spacing, difference in contrast, etc. You may also notice a couple other things that I'd also like to see in Budgie, such as:

- Updated Budgie Menu with an option for an icon-only view. (This would accompany a re-architecture of how desktop application tracking from gmenu to be less glitchy, centralizing search and listing to facilitate both views).
- Favorites that are separate from IconTasklist.
- Raven Weather widget (I'll dive into this in another issue that relates to Raven API, notifications like @EbonJaeger mentioned, and more) but the gist is this would come after the Raven API and we update all the widgets to use those.
- Thicker panel on some resolutions to make it easier to use and see, with downscaling icons to allow for gradual increasing rather than on fixed intervals (24x24, 32x32, 48x48, etc.)
- Iconography instead of labels for switch in Raven.

Alongside this, it would be interesting to think of ways of redesigning Budgie Desktop Settings. It wouldn't necessarily be a fully pluggable system (likely in B11 when we have a dedicated Control Center) but being able to integrate as an example all the Budgie Shuffler settings into the "Windows" section of Budgie Desktop Settings would be great, thoughts from Ubuntu Budgie folks appreciated on that).

I would like to stress that external themes would continue to be **encouraged**, **promoted** and **supported**. I will have an issue detailing things I would like to see there.

If you have feedback, please do provide it. Seriously. Nothing has changed yet and there may even be differences based on the implementation due to any limitations in GTK3 itself. This is a discussion, not an announcement. It has no given timeline, though I'd like to do this in 10.6 or latest 10.7 (but no timeframes have been set for those).

**Comment by EbonJaeger** [comment]
I'm really liking these mockups. Making the different parts of Raven more distinguished from each other I think is sorely needed.

In regard to the redesigned Budgie menu, in the first example, there are some blank spots above and below the top Discord entry. Is something going to go there, like a heading?

**Comment by JoshStrobl** [comment]
> In regard to the redesigned Budgie menu, in the first example, there are some blank spots above and below the top Discord entry. Is something going to go there, like a heading?

Yea that's just me derping with the mockup LUL. Headings are intended there.

**Comment by guillotjulien** [comment]
> I know this may excite many of you, but please let me do this :stuck_out_tongue:

That's where you're wrong, definitly not excited by the perspecive of doing CSS :stuck_out_tongue: 

I really like the design, especially the rounded corners. Maybe the dark theme controls and texts lack a bit of contrast which could be an issue for some people.

**Comment by EbonJaeger** [comment]
Gotcha!

A thought I had about Raven that I'm not sure if it should go here or in the Raven API issue is handling the case where there are more widgets than can fit on the screen. The way it is now is that the entirety of Raven is a ScrolledWindow; I would propose making the header (widgets and notification view buttons) always show at the top *outside* of the scrollable content, and then place everything else inside the scrolled window.

**Comment by JoshStrobl** [comment]
> Maybe the dark theme controls and texts lack a bit of contrast which could be an issue for some people.

Thanks. Can absolutely improve on the contrast to ensure it is more visible for folks!

**Comment by serebit** [comment]
Seconded the contrast note, though I think the contrast on the light theme is a bit *high* on both the appmenu and Raven while the contrast on the dark theme is a bit low on Raven and *way too low* on the appmenu. Everything else looks solid, though my personal preference for dark mode Raven would be light widgets on dark background rather than dark widgets on light background.

**Comment by JoshStrobl** [comment]
@serebit Not sure what you mean by "dark mode Raven would be light widgets on dark background rather than dark widgets on light background."

In this design, Raven in dark mode would have dark widgets on darker background as to not burn your eyes. The mockup is presenting both dark and light theming options, not reflective of a specific mix.

**Comment by serebit** [comment]
I figured I should've worded that differently. What I meant was dark widgets on a darker Raven background would be preferable—in the mockup shown, the widget backgrounds are darker than the Raven background. Hopefully that makes sense.

**Comment by clumsyfingers** [comment]
looks great
will it be possible to choose a dark budgie theme and light theme for the apps?

**Comment by JoshStrobl** [comment]
@clumsyfingers That's a good question actually and I think it ties into #27 a bit. Right now the idea would be they are coupled together, but I can see how it would be enticing to have a dark Budgie but light apps. Some of that is going to be based on the GTK Theme (if the built-in theme is disabled) but I'll update #27 to reflect a change from a boolean "built-in theme" to a ENUM state of DARK, LIGHT, DISABLED :)

**Comment by endumiuz** [comment]
> I figured I should've worded that differently. What I meant was dark widgets on a darker Raven background would be preferable—in the mockup shown, the widget backgrounds are darker than the Raven background. Hopefully that makes sense.

I did a quick recolour of the mockup (using my "mspaint" skills 😛) to see what it would look like with dark widgets on a darker background. Also tried to improve the contrasts a little.
![dark widgets on a darker background2](https://user-images.githubusercontent.com/7122445/148540341-cd2b8fea-697d-41d8-a293-5f7d82f1a3c9.png)

**Comment by serebit** [comment]
In the meantime, just in case we ship a new version of Budgie without the redesigned internal theme, I've pushed some changes to the default theme that make it more palatable. Less borders, better spacing, et cetera.

**Comment by Solarunit** [comment]
I think it would be nice to have an option to disable profile picture in the menu to keep it minimal. Also maybe  optional "panel" at the bottom of the menu with some buttons (reboot, shutdown, profile etc)

**Comment by JoshStrobl** [comment]
@Solarunit Clicking on your would present you with options. User indicator will still exist if folks want to use it.

**Comment by Cherryda** [comment]
Would it be possible to change the accent color? Other than that, this theme seems like a big improvement and makes Budgie look even more unique.

**Comment by Xmetalfanx** [comment]
I hate to clutter issues up with chat stuff but having issues with some themes looking off (say the menu works but the hightlight colors of what is selected or some border indicating the same thing was not showing) 

I am still trying to get my head around how the internet theme may work with other gtk themes... I am all for a good internal theme really ... I think what, the last user mentioned about a way to change the accent colors is a good idea.

**Comment by JoshStrobl** [comment]
I have no plans on implementing accent colors for the Budgie 10.x theming. It is something I want to do for Budgie 11 (maybe not MVP, we'll see depending on what direction the styling implementation goes).

**Comment by Xmetalfanx** [comment]
sounds good ... no matter the topic i rather you guys do what "you need to" for 10.x then switch to Budgie 11 ... meaning only spend as much time to add what needs to be added in your opinion to the 10.x series still

**Comment by serebit** [comment]
As an update to this:
- Josh is planning on forking an existing GTK theme and updating its style to fit our intended look instead of writing a new one from scratch. The most likely candidate is Materia, which has a license compatible with ours.
- If Josh's theme rewrite must be deferred past v10.8, then a recolor of the existing built-in theme will be merged as an interim step.

**Comment by JoshStrobl** [comment]
Closing as we're certainly not gonna bother doing this for 10 series. It's in maintenance, we'll make something super ~sexy~ fancy for 11 with QML.
